/**
 * Render visual starter templates to thumbnail HTML.
 *
 * Manually run: npm run render:thumbnails
 * Not wired into the Next.js build — see docs/TEMPLATE_STARTERS.md §7.4.
 *
 * Imports visual starter seeds, renders each to HTML via @templatical/renderer
 * + mjml, and writes the result to starterThumbnails.ts.
 */
import { renderToMjml } from '@templatical/renderer';
import mjml2html from 'mjml';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { TemplateContent } from '@templatical/types';
import { visualStarters } from '../components/templates/starters/visualStarters';

const __dirname = dirname(fileURLToPath(import.meta.url));

async function renderThumbnail(content: TemplateContent): Promise<string> {
  const mjml = await renderToMjml(content);
  const { html, errors } = await mjml2html(mjml, { minify: true });
  if (errors.length > 0) {
    throw new Error(`MJML errors for starter: ${errors.map((e) => e.message).join('; ')}`);
  }
  return html;
}

async function main(): Promise<void> {
  const entries: string[] = [];

  for (const seed of visualStarters) {
    if (seed.id.startsWith('blank-')) continue;
    const html = await renderThumbnail(seed.content);
    entries.push(`  '${seed.id}': \`${html.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`,`);
    console.log(`Rendered thumbnail for ${seed.id}`);
  }

  const output = `// AUTO-GENERATED by scripts/render-starter-thumbnails.ts — do not edit manually.
// Run: npm run render:thumbnails

export const starterThumbnails: Record<string, string> = {
${entries.join('\n')}
};
`;

  const targetPath = resolve(__dirname, '..', 'components', 'templates', 'starters', 'starterThumbnails.ts');
  writeFileSync(targetPath, output, 'utf-8');
  console.log(`Wrote ${targetPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
