export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  TEMPORARY_ERROR: 'TEMPORARY_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RECIPIENT_PREVIEW_CHANGED: 'RECIPIENT_PREVIEW_CHANGED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  CAMPAIGN_CREATION_BUSY: 'CAMPAIGN_CREATION_BUSY',
  NO_ELIGIBLE_RECIPIENTS: 'NO_ELIGIBLE_RECIPIENTS',
  RECIPIENT_ACTION_REQUIRED: 'RECIPIENT_ACTION_REQUIRED',
  UNSUPPORTED_FIELD: 'UNSUPPORTED_FIELD',
  RESEND_ENTRY_INVALID: 'RESEND_ENTRY_INVALID',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
